import random

def game():
    """
    This function allows the user to input their name, and input a number between 1 and 50, with 6 tries to guess the random number generated by the function.
    """

    num = random.randint(1, 50)
    tries = 0
    name = input('Hi, welcome to the guessing game, please enter your name: \n')

    print(f'Hi {name}, welcome. \n')

    while tries < 6:
        tries += 1
        guess = int(input('Please guess a number between one and 50:'))

        if guess < num:
            print('That guess is too low, try again. \n')
            
        elif guess > num:
            print('That guess is too high, try again. \n')

        else:
            print(f'Congrats, you guessed the number in {tries} tries!')
            break
    
    if guess != num:
        print(f'You lost, the random number was {num}.')

game()
